[workspace]
members = [".", "pigeon-core"]

[package]
name = "pigeon"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
pigeon-core = { path = "pigeon-core" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.12.0", features = [] }
tauri-plugin-log = "2"
tauri-plugin-http = { version = "=2.7.0", default-features = false, features = ["native-tls", "dangerous-settings", "unsafe-headers", "cookies", "http2", "charset", "system-proxy", "gzip", "brotli", "deflate", "multipart"] }
tauri-plugin-process = "2.4.0"
keyring = "3.6.3"
tauri-plugin-fs = { version = "2.6.0", features = ["watch"] }
tauri-plugin-dialog = "2.8.0"
tauri-plugin-persisted-scope = "2"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
rand = "0.9.5"
clap = { version = "4.5", features = ["derive"] }

[[bin]]
name = "pigeon"
path = "src/main.rs"

[[bin]]
name = "pigeon-cli"
path = "src/cli.rs"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-updater = "2.13.0"
